using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-008: checks aggregate type lines including partial and nested declarations.</summary>
internal sealed class AggregateTypeCodeLineCountAnalyzerTests
{
    private const string Id = "KLD0031";

    [Test]
    public async Task AggregateTypeLinesAtLimitPassAndOneOverReportsAsync()
    {
        foreach (var count in new[] { 199, 200, 201 })
        {
            var source = CreatePartialType(count);
            var findings = await NumericAnalyzerFixture.AnalyzeAsync(
                new AggregateTypeCodeLineCountAnalyzer(),
                ("/repo/src/First.cs", source.First),
                ("/repo/src/Second.cs", source.Second));
            if (count <= 200)
            {
                await Assert.That(findings).IsEmpty();
            }
            else
            {
                await NumericAnalyzerFixture.AssertSingleFindingAsync(
                    findings, Id, DiagnosticSeverity.Error, "/repo/src/First.cs", line: 0,
                    column: 0, span: new TextSpan(0, source.First.Length));
            }
        }
    }

    [Test]
    public async Task NestedTypeLinesCountInOuterAndInnerTypesAsync()
    {
        var source = CreateNestedType(201);
        var findings = await NumericAnalyzerFixture.AnalyzeAsync(
            new AggregateTypeCodeLineCountAnalyzer(), ("/repo/src/Nested.cs", source));
        await NumericAnalyzerFixture.AssertSingleFindingAsync(
            findings, Id, DiagnosticSeverity.Error, "/repo/src/Nested.cs", line: 0);
    }

    [Test]
    public async Task OversizedNestedTypeReportsForOuterAndInnerDeclarationsAsync()
    {
        var source = CreateOversizedInnerType(201);
        var findings = await NumericAnalyzerFixture.AnalyzeAsync(
            new AggregateTypeCodeLineCountAnalyzer(), ("/repo/src/Nested.cs", source));
        await Assert.That(findings.Length).IsEqualTo(2);
        await Assert.That(findings.All(finding => finding.Id == Id &&
            finding.Severity == DiagnosticSeverity.Error)).IsTrue();
        var lines = findings.Select(static finding =>
            finding.Location.GetLineSpan().StartLinePosition.Line).ToArray();
        await Assert.That(lines.Contains(0)).IsTrue();
        await Assert.That(lines.Contains(2)).IsTrue();
    }

    [Test]
    public async Task GeneratedPartialDeclarationDoesNotContributeToTypeTotalAsync()
    {
        var userDeclaration = WrapPartial("internal partial class Subject", 120, 0);
        var generatedDeclaration = "// <auto-generated/>\n" +
            WrapPartial("internal partial class Subject", 120, 120);
        var findings = await NumericAnalyzerFixture.AnalyzeAsync(
            new AggregateTypeCodeLineCountAnalyzer(),
            ("/repo/src/UserPart.cs", userDeclaration),
            ("/repo/src/Generated.g.cs", generatedDeclaration));
        await Assert.That(findings).IsEmpty();
    }

    [Test]
    public async Task GeneratedTypeSourceIsIgnoredByRoslynPolicyAsync()
    {
        var source = CreateNestedType(201);
        var findings = await NumericAnalyzerFixture.AnalyzeAsync(
            new AggregateTypeCodeLineCountAnalyzer(), ("/repo/src/Generated.g.cs", source));
        await Assert.That(findings).IsEmpty();
    }

    [Test]
    public async Task DisabledTextAndMultilineRawTokenInsideTypeCountAsync()
    {
        var fields = Enumerable.Range(0, 188)
            .Select(static index => $"    private int Value{index};");
        var rawLines = Enumerable.Range(0, 8).Select(static index => $"    literal{index}");
        var source = "internal sealed class Subject\n{\n" + string.Join("\n", fields) +
            "\n    private const string Text = \"\"\"\n" + string.Join("\n", rawLines) +
            "\n    \"\"\";\n#if NEVER_DEFINED\nthis disabled source counts\n#endif\n}";
        var findings = await NumericAnalyzerFixture.AnalyzeAsync(
            new AggregateTypeCodeLineCountAnalyzer(), ("/repo/src/Subject.cs", source));
        await NumericAnalyzerFixture.AssertSingleFindingAsync(
            findings, Id, DiagnosticSeverity.Error, "/repo/src/Subject.cs", line: 0,
            column: 0, span: new TextSpan(0, source.Length));
    }

    [Test]
    public async Task MultilineCommentInsideTypeAddsNoCodeLinesAsync()
    {
        var fields = Enumerable.Range(0, 196)
            .Select(static index => $"    private int Value{index};");
        var source = "internal sealed class Subject\n{\n" + string.Join("\n", fields) +
            "\n    /*\n        comment line one\n        comment line two\n        comment line three\n    */\n}";
        var findings = await NumericAnalyzerFixture.AnalyzeAsync(
            new AggregateTypeCodeLineCountAnalyzer(), ("/repo/src/Subject.cs", source));
        await Assert.That(findings).IsEmpty();
    }

    [Test]
    public async Task OnlyExactCoreDatabaseEngineTypeGetsExpiringExceptionAsync()
    {
        await Assert.That(AggregateTypeLimitException.IsAllowed(
            "KeyLoad.Core", "KeyLoad.Core.DatabaseEngine", new DateOnly(2026, 10, 31))).IsTrue();
        await Assert.That(AggregateTypeLimitException.IsAllowed(
            "KeyLoad.Core", "KeyLoad.Core.DatabaseEngine", new DateOnly(2026, 11, 1))).IsFalse();
        await Assert.That(AggregateTypeLimitException.IsAllowed(
            "KeyLoad.Other", "KeyLoad.Core.DatabaseEngine", new DateOnly(2026, 10, 31))).IsFalse();
        await Assert.That(AggregateTypeLimitException.IsAllowed(
            "KeyLoad.Core", "KeyLoad.DatabaseEngine", new DateOnly(2026, 10, 31))).IsFalse();
        await Assert.That(AggregateTypeLimitException.IsAllowed(
            "KeyLoad.Core", "KeyLoad.OtherType", new DateOnly(2026, 10, 31))).IsFalse();
    }

    private static (string First, string Second) CreatePartialType(int count)
    {
        const string firstHeader = "internal partial class Subject";
        const string secondHeader = "internal partial class Subject";
        var firstLines = (count + 1) / 2;
        var first = WrapPartial(firstHeader, firstLines, 0);
        var second = WrapPartial(secondHeader, count - firstLines, firstLines);
        return (first, second);
    }

    private static string WrapPartial(string header, int tokenLineCount, int memberOffset)
    {
        var members = Enumerable.Range(memberOffset, tokenLineCount - 3)
            .Select(static index => $"    private int Value{index};");
        return header + "\n{\n" + string.Join("\n", members) + "\n}";
    }

    private static string CreateNestedType(int count)
    {
        var outerLines = Enumerable.Range(0, count - 5)
            .Select(static index => $"    private int Value{index};");
        return "internal class Outer\n{\n" + string.Join("\n", outerLines) +
            "\n    internal class Inner\n    {\n        private int Value;\n    }\n}";
    }

    private static string CreateOversizedInnerType(int count)
    {
        var innerLines = Enumerable.Range(0, count - 3)
            .Select(static index => $"        private int Value{index};");
        return "internal class Outer\n{\n    internal class Inner\n    {\n" +
            string.Join("\n", innerLines) + "\n    }\n}";
    }
}
