using Microsoft.CodeAnalysis;

namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-004: verifies literal machine key tests with real compiler fixtures.</summary>
internal sealed class LiteralMachineKeyTests
{
    private const string Id = LiteralMachineKeyAnalyzer.DiagnosticId;

    /// <summary>Verifies inline dictionary key reports located error.</summary>
    [Test]
    public async Task InlineDictionaryKeyReportsLocatedErrorAsync()
    {
        const string source = """
            using System.Collections.Generic;
            internal static class Subject
            {
                internal static int Read(Dictionary<string, int> values) => values["revision"];
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new LiteralMachineKeyAnalyzer(), source);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            source, "revision");
    }

    /// <summary>Verifies json attribute key reports located error.</summary>
    [Test]
    public async Task JsonAttributeKeyReportsLocatedErrorAsync()
    {
        const string source = """
            using System.Text.Json.Serialization;
            internal sealed class Subject
            {
                [JsonPropertyName("scope")]
                public string Scope { get; init; } = string.Empty;
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new LiteralMachineKeyAnalyzer(), source);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            source, "scope");
    }

    /// <summary>Verifies constant and human text are allowed.</summary>
    [Test]
    public async Task ConstantAndHumanTextAreAllowedAsync()
    {
        const string source = """
            using System;
            using System.Collections.Generic;
            internal static class Keys { internal const string Revision = "revision"; }
            internal static class Subject
            {
                internal static int Read(Dictionary<string, int> values)
                {
                    Console.WriteLine("Human-facing message");
                    return values[Keys.Revision];
                }
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new LiteralMachineKeyAnalyzer(), source);
        await Assert.That(findings).IsEmpty();
    }

    /// <summary>Verifies generated code is ignored.</summary>
    [Test]
    public async Task GeneratedCodeIsIgnoredAsync()
    {
        const string source = """
            // <auto-generated/>
            using System.Collections.Generic;
            internal static class Subject
            {
                internal static int Read(Dictionary<string, int> values) => values["revision"];
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new LiteralMachineKeyAnalyzer(), source,
            path: AnalyzerFixture.GeneratedPath);
        await Assert.That(findings).IsEmpty();
    }
}
