namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-031: runtime ownership includes infrastructure and benchmarks without admitting test data.</summary>
internal sealed class MagicRuntimeSourceBoundaryTests
{
    private const string BenchmarkAssembly = "KeyLoad.Benchmarks";
    private const string AppHostAssembly = "KeyLoad.AppHost";
    private const string AnalyzerAssembly = "KeyLoad.Analyzers";

    [Test]
    [Arguments(AnalyzerFixture.ServerAssembly)]
    [Arguments(AnalyzerFixture.CoreAssembly)]
    [Arguments(AppHostAssembly)]
    [Arguments(BenchmarkAssembly)]
    public async Task RuntimeAssembliesIncludeInfrastructureAndBenchmarkPoliciesAsync(string assemblyName)
    {
        const string durationSource = """
            internal static class Subject
            {
                internal static System.TimeSpan Execute() => System.TimeSpan.FromSeconds([|1d|]);
            }
            """;
        const string stringSource = """
            internal static class Subject
            {
                internal static bool Execute(string value) => value == [|"ready"|];
            }
            """;

        await MagicRuntimeFixture.AssertDurationAsync(durationSource, assemblyName);
        await MagicRuntimeFixture.AssertStringAsync(stringSource, assemblyName);
    }

    [Test]
    [Arguments(AnalyzerFixture.UnitTestAssembly)]
    [Arguments(AnalyzerFixture.CoreTestAssembly)]
    [Arguments(AnalyzerFixture.ExternalAssembly)]
    [Arguments(AnalyzerAssembly)]
    public async Task TestDataExternalAndAnalyzerInfrastructureAreOutsideNewRuntimeRulesAsync(string assemblyName)
    {
        const string source = """
            internal static class Subject
            {
                internal static bool Execute(string value)
                {
                    System.Threading.Tasks.Task.Delay(1);
                    return value == "ready";
                }
            }
            """;

        await MagicRuntimeFixture.AssertDurationAsync(source, assemblyName);
        await MagicRuntimeFixture.AssertStringAsync(source, assemblyName);
    }

    [Test]
    public async Task GeneratedHeaderExcludesBothNativePolicyContextsAsync()
    {
        const string source = """
            // <auto-generated/>
            internal static class Subject
            {
                internal static bool Execute(string value)
                {
                    System.Threading.Tasks.Task.Delay(1);
                    return value == "ready";
                }
            }
            """;

        await MagicRuntimeFixture.AssertDurationAsync(source);
        await MagicRuntimeFixture.AssertStringAsync(source);
    }

    [Test]
    public async Task GeneratedFileNameExcludesBothRulesWithoutHeaderAsync()
    {
        const string source = """
            internal static class Subject
            {
                internal static bool Execute(string value)
                {
                    System.Threading.Tasks.Task.Delay(1);
                    return value == "ready";
                }
            }
            """;

        await MagicRuntimeFixture.AssertDurationAsync(source, path: AnalyzerFixture.GeneratedPath);
        await MagicRuntimeFixture.AssertStringAsync(source, path: AnalyzerFixture.GeneratedPath);
    }
}
