using Microsoft.CodeAnalysis;

namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-004: verifies program composition root tests with real compiler fixtures.</summary>
internal sealed class ProgramCompositionRootTests
{
    private const string Id = ProgramCompositionRootAnalyzer.DiagnosticId;
    private const string AggregateSource = """
        using Microsoft.AspNetCore.Builder;
        using Microsoft.Extensions.DependencyInjection;
        internal static class KeyLoadHosting
        {
            internal static IServiceCollection AddKeyLoadServer(this IServiceCollection services)
            {
                services.AddSingleton<System.TimeProvider>(System.TimeProvider.System);
                return services;
            }
            internal static WebApplication UseKeyLoadServer(this WebApplication app)
            {
                app.UseRouting();
                return app;
            }
            internal static WebApplication MapKeyLoadApi(this WebApplication app)
            {
                app.MapGet("/health", () => "ok");
                return app;
            }
        }
        """;

    /// <summary>Verifies aggregate composition is allowed.</summary>
    [Test]
    public async Task AggregateCompositionIsAllowedAsync()
    {
        const string source = """
            using Microsoft.AspNetCore.Builder;
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddKeyLoadServer();
            var app = builder.Build();
            app.UseKeyLoadServer();
            app.MapKeyLoadApi();
            app.Run();
            public partial class Program;
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new ProgramCompositionRootAnalyzer(),
            source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ProgramPath, executable: true,
            additionalSource: AggregateSource);
        await Assert.That(findings).IsEmpty();
    }

    /// <summary>Verifies concrete registration reports located error.</summary>
    [Test]
    public async Task ConcreteRegistrationReportsLocatedErrorAsync()
    {
        const string source = """
            using Microsoft.AspNetCore.Builder;
            using Microsoft.Extensions.DependencyInjection;
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddSingleton<System.TimeProvider>(System.TimeProvider.System);
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new ProgramCompositionRootAnalyzer(),
            source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ProgramPath, executable: true,
            additionalSource: AggregateSource);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            source, "builder.Services.AddSingleton", AnalyzerFixture.ProgramPath);
    }

    /// <summary>Verifies helper declaration reports located error.</summary>
    [Test]
    public async Task HelperDeclarationReportsLocatedErrorAsync()
    {
        const string source = """
            using Microsoft.AspNetCore.Builder;
            var builder = WebApplication.CreateBuilder();
            static void ConfigureServices() => System.Console.WriteLine("configured");
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new ProgramCompositionRootAnalyzer(),
            source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ProgramPath, executable: true,
            additionalSource: AggregateSource);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            source, "static void ConfigureServices", AnalyzerFixture.ProgramPath);
    }

    /// <summary>Verifies non program file is ignored.</summary>
    [Test]
    public async Task NonProgramFileIsIgnoredAsync()
    {
        const string source = """
            using Microsoft.AspNetCore.Builder;
            using Microsoft.Extensions.DependencyInjection;
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddSingleton<System.TimeProvider>(System.TimeProvider.System);
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new ProgramCompositionRootAnalyzer(),
            source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ServerHostingPath, executable: true,
            additionalSource: AggregateSource);
        await Assert.That(findings).IsEmpty();
    }

    /// <summary>Verifies generated program is ignored.</summary>
    [Test]
    public async Task GeneratedProgramIsIgnoredAsync()
    {
        const string source = """
            // <auto-generated/>
            using Microsoft.AspNetCore.Builder;
            using Microsoft.Extensions.DependencyInjection;
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddSingleton<System.TimeProvider>(System.TimeProvider.System);
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new ProgramCompositionRootAnalyzer(),
            source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ProgramPath, executable: true,
            additionalSource: AggregateSource);
        await Assert.That(findings).IsEmpty();
    }
}
