using Microsoft.CodeAnalysis;

namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-TIME-004: native compiler clock bypass regressions.</summary>
internal sealed class SystemClockElapsedTests
{
    [Test]
    [Arguments("Clock.GetTimestamp()")]
    [Arguments("Clock.GetElapsedTime(0)")]
    [Arguments("Clock.StartNew()")]
    [Arguments("Clock.Frequency")]
    [Arguments("Clock.IsHighResolution")]
    [Arguments("Environment.TickCount")]
    [Arguments("Environment.TickCount64")]
    [Arguments("new Clock()")]
    public async Task DirectTimingAccessReportsExactLocatedError(string expression)
    {
        const string template = """
            using System;
            using Clock = System.Diagnostics.Stopwatch;
            internal static class Subject
            {
                internal static object Run() => EXPRESSION;
            }
            """;
        const string placeholder = "EXPRESSION";
        var source = template.Replace(placeholder, expression, StringComparison.Ordinal);
        var findings = await AnalyzerFixture.AnalyzeAsync(new SystemClockAccessAnalyzer(), source);
        await AnalyzerFixture.AssertFindingAsync(findings, SystemClockAccessAnalyzer.DiagnosticId,
            DiagnosticSeverity.Error, source, expression);
        await Assert.That(findings[0].Location.SourceSpan.Start)
            .IsEqualTo(source.IndexOf(expression, StringComparison.Ordinal));
        await Assert.That(findings[0].Location.SourceSpan.Length).IsEqualTo(expression.Length);
    }

    [Test]
    public async Task ProviderTimingAndUnrelatedSymbolsRemainAllowed()
    {
        const string source = """
            using System;
            internal static class Subject
            {
                internal static TimeSpan Run(TimeProvider clock)
                {
                    var started = clock.GetTimestamp();
                    _ = clock.TimestampFrequency;
                    var unrelated = new Stopwatch();
                    _ = unrelated.GetTimestamp();
                    _ = unrelated.Frequency;
                    return clock.GetElapsedTime(started);
                }
            }
            internal sealed class Stopwatch
            {
                internal long GetTimestamp() => 0;
                internal long Frequency => 1;
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new SystemClockAccessAnalyzer(), source);
        await Assert.That(findings).IsEmpty();
    }

    [Test]
    public async Task GeneratedElapsedTimingIsIgnored()
    {
        const string source = """
            // <auto-generated/>
            internal static class Subject
            {
                internal static long Run() => System.Diagnostics.Stopwatch.GetTimestamp();
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new SystemClockAccessAnalyzer(), source,
            path: AnalyzerFixture.GeneratedPath);
        await Assert.That(findings).IsEmpty();
    }
}
