namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-025: rejects object and Monitor synchronization with exact semantic locations.</summary>
internal sealed class TypedSynchronizationTests
{
    [Test]
    [Arguments("object", "new()", "gate")]
    [Arguments("System.Threading.Lock", "new()", "(object)gate")]
    [Arguments("string", "\"identity\"", "gate")]
    [Arguments("object", "new()", "this")]
    public async Task NonNativeLockExpressionsAreRejectedAsync(string type, string initializer, string expression)
    {
        var source = $$"""
            internal sealed class Subject
            {
                private readonly {{type}} gate = {{initializer}};
                internal void Update()
                {
                    lock ({{expression}}) { }
                }
            }
            """;

        // The occurrence in the lock expression is distinct from the field declaration.
        var findings = await AnalyzerFixture.AnalyzeAsync(new TypedSynchronizationAnalyzer(), source);
        await AnalyzerFixture.AssertFindingAsync(findings, TypedSynchronizationAnalyzer.DiagnosticId,
            Microsoft.CodeAnalysis.DiagnosticSeverity.Error, source, $"lock ({expression})");
        var expectedStart = source.IndexOf($"lock ({expression})", StringComparison.Ordinal) + "lock (".Length;
        await Assert.That(findings[0].Location.SourceSpan.Start).IsEqualTo(expectedStart);
        await Assert.That(findings[0].Location.SourceSpan.Length).IsEqualTo(expression.Length);
    }

    [Test]
    public async Task NativeLockAliasAndOrdinaryIdentityObjectsAreAllowedAsync()
    {
        const string source = """
            using NativeGate = System.Threading.Lock;
            internal sealed class Subject
            {
                private readonly NativeGate gate = new();
                private readonly object identity = new();
                private int updates;
                internal object Update()
                {
                    lock (gate) { updates++; }
                    return identity;
                }
            }
            """;

        await TypedSynchronizationFixture.AssertAllowedAsync(source);
    }

    [Test]
    public async Task ObjectAliasLockIsRejectedAsync()
    {
        const string source = """
            using Identity = System.Object;
            internal sealed class Subject(Identity gate)
            {
                internal void Update() { lock ((Identity)gate) { } }
            }
            """;

        await TypedSynchronizationFixture.AssertFindingAsync(source, "(Identity)gate");
    }

    [Test]
    [Arguments("System.Threading.Monitor.Enter(gate)")]
    [Arguments("GateMonitor.Exit(gate)")]
    [Arguments("GateMonitor.TryEnter(gate, 0)")]
    [Arguments("GateMonitor.Wait(gate, 0)")]
    [Arguments("GateMonitor.Pulse(gate)")]
    [Arguments("GateMonitor.PulseAll(gate)")]
    [Arguments("GateMonitor.IsEntered(gate)")]
    [Arguments("Enter(gate)")]
    public async Task MonitorApiCallsAndAliasesAreRejectedAsync(string invocation)
    {
        var source = $$"""
            using GateMonitor = System.Threading.Monitor;
            using static System.Threading.Monitor;
            internal sealed class Subject(object gate)
            {
                internal void Update() { {{invocation}}; }
            }
            """;

        await TypedSynchronizationFixture.AssertFindingAsync(source, invocation);
    }

    [Test]
    public async Task AwaitedSemaphoreAndNativeLockScopesAreAllowedOutsideGrainsAsync()
    {
        const string source = """
            using System.Threading;
            using System.Threading.Tasks;
            internal sealed class Subject
            {
                private readonly SemaphoreSlim asynchronousGate = new(1, 1);
                private readonly Lock synchronousGate = new();
                internal async Task UpdateAsync(CancellationToken cancellationToken)
                {
                    await asynchronousGate.WaitAsync(cancellationToken);
                    try { await Task.Yield(); }
                    finally { asynchronousGate.Release(); }
                }
                internal void Update()
                {
                    using (synchronousGate.EnterScope()) { }
                }
            }
            """;

        await TypedSynchronizationFixture.AssertAllowedAsync(source);
    }

    [Test]
    [Arguments(AnalyzerFixture.GeneratedPath)]
    [Arguments(AnalyzerFixture.ContractPath)]
    public async Task GeneratedObjectLocksAndMonitorCallsAreExcludedAsync(string path)
    {
        const string source = """
            // <auto-generated/>
            internal sealed class Subject(object gate)
            {
                internal void Update()
                {
                    lock (gate) { System.Threading.Monitor.Pulse(gate); }
                }
            }
            """;

        await TypedSynchronizationFixture.AssertAllowedAsync(source, path);
    }

    [Test]
    public async Task GeneratedFileNameExcludesLocksWithoutGeneratedHeaderAsync()
    {
        const string source = """
            internal sealed class Subject(object gate)
            {
                internal void Update() { lock (gate) { System.Threading.Monitor.Pulse(gate); } }
            }
            """;

        await TypedSynchronizationFixture.AssertAllowedAsync(source, AnalyzerFixture.GeneratedPath);
    }
}
