namespace KeyLoad.Core.Features.ClusterRouting.Contracts;

/// <summary>One first-issued body until settled, then its exact immutable native outcome proof.</summary>
[Orleans.GenerateSerializer, Orleans.Alias(PartitionMoveParentContractNames.PartitionMoveParentPhaseAlias)]
internal sealed record PartitionMoveParentPhase(
    [property: Orleans.Id(0)] int Version,
    [property: Orleans.Id(1)] Guid MoveId,
    [property: Orleans.Id(2)] PartitionRef Partition,
    [property: Orleans.Id(3)] Guid OriginalPhaseCommandId,
    [property: Orleans.Id(4)] PartitionMovePeerStage Stage,
    [property: Orleans.Id(5)] int PageOrdinal,
    [property: Orleans.Id(6)] string OriginalBodyDigest,
    [property: Orleans.Id(7)] PartitionMovePhaseCommand? OriginalPhase,
    [property: Orleans.Id(8)] PartitionMoveJournalReceipt? OriginalAuthorization,
    [property: Orleans.Id(9)] OperationResult? OriginalResult,
    [property: Orleans.Id(10)] PartitionMoveImageDescriptor? OriginalDescriptor,
    [property: Orleans.Id(11)] PartitionMoveSourceFenceRecord? OriginalFence,
    [property: Orleans.Id(12)] PartitionMoveJournalReceipt AdmissionCheckpointReceipt,
    [property: Orleans.Id(13)] PartitionMoveJournalReceipt? ObservationCheckpointReceipt,
    [property: Orleans.Id(14)] PartitionMovePhaseGrant? OriginalGrant,
    [property: Orleans.Id(15)] PhysicalShardRecord OriginalReceiverOwner,
    [property: Orleans.Id(16)] DateTimeOffset OriginalExpiresAt,
    [property: Orleans.Id(17)] PartitionMoveCaptureWitness? OriginalCaptureWitness = null,
    [property: Orleans.Id(18)] Guid OriginalRequestNonce = default,
    [property: Orleans.Id(19)] PartitionMoveJournalReceipt? CaptureProofCheckpointReceipt = null,
    [property: Orleans.Id(20)] string OriginalPhaseIdentityDigest = PartitionMoveParentContractNames.AbsentIdentityDigest,
    [property: Orleans.Id(21)] PartitionMoveAuthenticatedOutcomeWitness? OriginalOutcomeWitness = null,
    [property: Orleans.Id(22)] Guid OriginalCaptureReleaseNonce = default,
    [property: Orleans.Id(23)] PartitionMoveParentCancellation? Cancellation = null,
    [property: Orleans.Id(24)] long OriginalIssuancePolicyEpoch = PartitionMoveParentContractNames.UnissuedPolicyEpoch,
    [property: Orleans.Id(25)] PartitionMoveReceiverIssuanceWitness? OriginalReceiverIssuanceWitness = null,
    [property: Orleans.Id(26)] PartitionMoveJournalReceipt? ReceiverIssuanceCheckpointReceipt = null,
    [property: Orleans.Id(27)] PartitionMoveReceiverSourceWitness? OriginalReceiverSourceWitness = null,
    [property: Orleans.Id(28)] PartitionMoveJournalReceipt? ReceiverSourceCheckpointReceipt = null,
    [property: Orleans.Id(29)] PartitionMoveReceiverIssuePacket? OriginalReceiverIssuePacket = null,
    [property: Orleans.Id(30)] PartitionMoveJournalReceipt? ReceiverIssuePacketCheckpointReceipt = null,
    [property: Orleans.Id(31)] long CleanupGeneration = PartitionMoveParentContractNames.InitialCleanupGeneration,
    [property: Orleans.Id(32)] PartitionMoveRetireCancellationWitness? RetireCancellation = null,
    [property: Orleans.Id(33)] PartitionMoveRetireCancellationAttempt? RetireCancellationAttempt = null);
