<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/KeyLoad.AppHost/KeyLoad.AppHost.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Client/KeyLoad.Client.csproj" />
    <ProjectReference Include="../KeyLoad.CrashHost/KeyLoad.CrashHost.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../../src/KeyLoad.Replication/KeyLoad.Replication.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Server/KeyLoad.Server.csproj" IsAspireProjectResource="false" />
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="ModelContextProtocol.Core" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
</Project>
