<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../KeyLoad.Abstractions/KeyLoad.Abstractions.csproj" />
    <ProjectReference Include="../KeyLoad.Diagnostics/KeyLoad.Diagnostics.csproj" />
    <ProjectReference Include="../KeyLoad.Storage.IO/KeyLoad.Storage.IO.csproj" />
    <InternalsVisibleTo Include="KeyLoad.Server" />
    <InternalsVisibleTo Include="KeyLoad.UnitTests" />
    <InternalsVisibleTo Include="KeyLoad.ComparisonTests" />
    <InternalsVisibleTo Include="KeyLoad.CrashHost" />
    <PackageReference Include="Microsoft.Orleans.Serialization" />
    <PackageReference Include="Microsoft.Orleans.CodeGenerator" PrivateAssets="all" />
    <PackageReference Include="ZoneTree" />
    <PackageReference Include="ManagedCode.Storage.FileSystem" />
  </ItemGroup>
</Project>
