<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="../../benchmarks/KeyLoad.ComparisonHost/Features/BenchmarkComparisons/Configuration/native-execution.json" Link="native-execution.json" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="../../src/KeyLoad.Client/KeyLoad.Client.csproj" />
    <ProjectReference Include="../../src/KeyLoad.AppHost/KeyLoad.AppHost.csproj" />
    <ProjectReference Include="../../benchmarks/KeyLoad.Comparisons/KeyLoad.Comparisons.csproj" />
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="ModelContextProtocol.Core" />
  </ItemGroup>
</Project>
