namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

internal static class SiteAnalyzerCoverageTokens
{
    internal const string ScriptRelativePath = "scripts/Features/CodeQuality/site-analyzer-coverage.ps1";
    internal const string ContractRelativePath = "scripts/Features/CodeQuality/site-analyzer-coverage.contract.json";
    internal const string RepositoryVariable = "GITHUB_WORKSPACE";
    internal const string GitHubRevisionVariable = "GITHUB_SHA";
    internal const string SiteRevisionVariable = "KEYLOAD_SITE_SOURCE_REVISION";
    internal const string ProcessIsolationKey = "site-analyzer-coverage-powershell";
    internal const string SiteRevisionA = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    internal const string TriggerRevisionB = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    internal const string EmptyRevision = "";
    internal const string WhitespaceRevision = "   ";
    internal const string MalformedRevision = "0123456789abcdef";
    internal const string UppercaseRevision = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    internal static readonly string[] InvalidDedicatedRevisions = [EmptyRevision, WhitespaceRevision, MalformedRevision, UppercaseRevision];
    internal const string CoverageDirectoryName = "site-analyzer-coverage-tests";
    internal const string ManifestName = "source-manifest.json";
    internal const string SummaryName = "report.json";
    internal const string InputName = "coverage.cobertura.xml";
    internal const string SettingsSourcePath = "scripts/Features/CodeQuality/site-analyzer-coverage.settings.xml";
    internal const string SettingsCopyName = "coverage.config.xml";
    internal const string HelperDirectory = "scripts/Features/CodeQuality";
    internal const string HelperFilePattern = "site-analyzer-coverage*.ps1";
    internal const string RepoDirectoryName = "repo";
    internal const string EvidenceDirectoryName = "evidence";
    internal const string SolutionFileName = "KeyLoad.slnx";
    internal const string NoLogo = "-NoLogo";
    internal const string NoProfile = "-NoProfile";
    internal const string NonInteractive = "-NonInteractive";
    internal const string CommandArgument = "-Command";
    internal const string PowerShellRuntimeCommand = "[Environment]::Version.ToString(); [string]$PSVersionTable.PSVersion";
    internal const int RuntimeVersionOutputIndex = 0;
    internal const int PowerShellVersionOutputIndex = 1;
    internal const string FileArgument = "-File";
    internal const string PathProperty = "path";
    internal const string ClassificationProperty = "classification";
    internal const string RepositoryUnavailableMessage = "Repository root is not available to analyzer coverage tests.";
    internal const string ProcessOutputLimitMessage = "Coverage PowerShell output exceeded its bounded test limit.";
    internal const string ChangedSourceContent = "changed";
    internal const string OtherModuleName = "Other.Module";
    internal const string JsonSummaryProperty = "module";
    internal const string JsonPassedProperty = "passed";
    internal const string JsonSourceRevision = "sourceRevision";
    internal const string JsonRuntimeVersion = "runtimeVersion";
    internal const string JsonPowerShellVersion = "pwshVersion";
    internal const string JsonGateScripts = "gateScripts";
    internal const string JsonSettingsConfigPath = "settingsConfigPath";
    internal const string JsonSettingsConfigHash = "settingsConfigSha256";
    internal const string JsonNativeReportHash = "nativeReportSha256";
    internal const string JsonLinesValid = "linesValid";
    internal const string JsonLinesCovered = "linesCovered";
    internal const string JsonBranchesCovered = "branchesCovered";
    internal const string JsonBranchesValid = "branchesValid";
    internal const string JsonDiagnostic = "diagnostic";
    internal const string JsonPassed = "passed";
    internal const string JsonFiles = "files";
    internal const string JsonCriticalPipelines = "criticalPipelines";
    internal const string JsonSha256 = "sha256";
    internal const string JsonSources = "sources";
    internal const string JsonConfiguration = "configuration";
    internal const string JsonPipelines = "pipelines";
    internal const int ExpectedSourceCount = 36;
    internal const int ExpectedDeclarationCount = 7;
    internal const int ExpectedConfigurationCount = 8;
    internal const int ExpectedGateScriptCount = 4;
    internal const int ExpectedPipelineCount = 15;
    internal const int ExpectedUniqueLineCount = 290;
    internal const int ExpectedBelowLineCoverage = 229;
    internal const int ExpectedExactLineCoverage = 232;
    internal const int ExpectedAboveLineCoverage = 234;
    internal const int ExpectedDefaultBranchesCovered = 2030;
    internal const int ExpectedDefaultBranchesValid = 2900;
    internal const int HashLength = 64;
    internal const string JsonFailuresProperty = "failures";
    internal const string ErrorNoRevision = "Coverage source revision must be a lowercase 40-character commit SHA.";
    internal const string ErrorInvalidManifest = "Prepared source manifest does not match the current candidate.";
    internal const string ModuleLineFailure = "module line threshold";
    internal const string ModuleBranchFailure = "module branch threshold";
    internal const string CriticalPipelineId = "KLD0013";
    internal const string CriticalPipelineSource = "src/KeyLoad.Analyzers/Features/CodeQuality/Analyzers/ProgramEndpointMappingAnalyzer.cs";
    internal const string AnalyzerDirectoryRelativePath = "src/KeyLoad.Analyzers/Features/CodeQuality/Analyzers";
    internal const string AnalysisDirectoryRelativePath = "src/KeyLoad.Analyzers/Features/CodeQuality/Analysis";
    internal const string MissingLinkTargetRelativePath = "src/KeyLoad.Analyzers/Features/CodeQuality/Analyzers/MissingTarget.cs";
    internal const string CoveragePackagePrefix = "<coverage><packages><package name=\"";
    internal const string CoveragePackagePrefixWithSource = "<coverage><sources><source>";
    internal const string SourceRepeatOpen = "</source><source>";
    internal const string SourceToPackage = "</source></sources><packages><package name=\"";
    internal const string CoveragePackageMiddle = "\"><classes>";
    internal const string ClassNameValue = "CoverageFixture";
    internal const string DuplicateClassNameValue = "CoverageFixtureDuplicate";
    internal const string CounterOneText = "1";
    internal const int LinesPerSource = 10;
    internal const int RequiredPipelinePercent = 90;
    internal const int RequiredModuleLinePercent = 80;
    internal const int RequiredModuleBranchPercent = 70;
    internal const int CoveragePercentageScale = 100;
    internal const int ExactLineBoundary = 80;
    internal const int BelowLineBoundary = 79;
    internal const int AboveLineBoundary = 81;
    internal const int ExactBranchBoundary = 70;
    internal const int BelowBranchBoundary = 69;
    internal const int AboveBranchBoundary = 71;
    internal const int ExactPipelineBoundary = 9;
    internal const int BelowPipelineBoundary = 8;
    internal const int AbovePipelineBoundary = 10;
    internal const int BranchDenominator = 100;
    internal const long MaximumCoverageCounter = long.MaxValue;
    internal const long HugeBranchDenominator = 9223372036854775800L;
    internal const long BelowHugeBranchCovered = 6456360425798343059L;
    internal const long ExactHugeBranchCovered = 6456360425798343060L;
    internal const int SingleBranchSourceCount = 1;
    internal const int OverflowBranchSourceCount = 2;
    internal const int ZeroBranchDenominator = 0;
    internal const int DefaultBranchCovered = 70;
    internal const int DefaultBranchTotal = 100;
    internal const int SuccessExitCode = 0;
    internal const int ProcessTimeoutMilliseconds = 30000;
    internal const int CleanupTimeoutMilliseconds = 3000;
    internal const int MaximumConcurrentPowerShellProcesses = 2;
    internal const int ProcessOutputBufferSize = 4096;
    internal const int MaximumProcessOutputCharacters = 1048576;
    internal const int CounterZero = 0;
    internal const int CounterOne = 1;
    internal const int CounterTwo = 2;
    internal const int FirstLineNumber = 1;
    internal const string ConfigFileRelativePath = "Directory.Build.props";
    internal const string StaleEvidenceMarker = "stale";
    internal const string ZeroPercent = "0";
    internal const string GateHelperRelativePath = "scripts/Features/CodeQuality/site-analyzer-coverage.shared.ps1";
    internal const string ModuleName = "KeyLoad.Analyzers";
    internal const string ExecutableKind = "executable";
    internal const string XmlDeclaration = "<?xml version=\"1.0\" encoding=\"utf-8\"?>";
    internal const string XmlClassElement = "class";
    internal const string XmlLineElement = "line";
    internal const string XmlFilenameAttribute = "filename";
    internal const string XmlNumberAttribute = "number";
    internal const string PackageClose = "</classes></package></packages></coverage>";
    internal const string ClassOpen = "<class name=\"";
    internal const string ClassFileSeparator = "\" filename=\"";
    internal const string ClassMiddle = "\">";
    internal const string LinesOpen = "<lines>";
    internal const string MethodsBlock = "<methods><method name=\"FixtureMethod\"><lines><line number=\"1\" hits=\"999\"/></lines></method></methods>";
    internal const string ClassClose = "</lines></class>";
    internal const string LineOpen = "<line number=\"";
    internal const string LineNumberOneAttribute = "number=\"1\" hits=\"";
    internal const string LineNumberZeroAttribute = "number=\"0\" hits=\"";
    internal const string LineHits = "\" hits=\"";
    internal const string BranchTrue = "\" branch=\"true\" condition-coverage=\"";
    internal const string BranchTrueNative = "\" branch=\"True\" condition-coverage=\"";
    internal const string BranchFalseSuffix = "\" branch=\"false\"/>";
    internal const string BranchFalseNativeSuffix = "\" branch=\"False\"/>";
    internal const string CoveragePairOpen = "% (";
    internal const char PairSlash = '/';
    internal const string PairClose = ")\"/>";
    internal const string LineClose = "\"/>";
    internal const string DtdPrefix = "<!DOCTYPE coverage [<!ENTITY payload \"expanded\">]>";
    internal const string MalformedInteger = "many";
    internal const string UnsafePath = "../outside.cs";
    internal const string UnsafePathError = "Contract or Cobertura path is unsafe or outside the repository.";
    internal const string UnknownSourcePath = "src/KeyLoad.Analyzers/Features/CodeQuality/Unknown.cs";
    internal const string ParentPathSegment = "..";
    internal const string CounterOverflowFailure = "Coverage counter aggregation overflowed Int64.";
    internal const string InvalidBranchBoolean = "branch=\"invalid\"";
    internal const string LowercaseTrue = "branch=\"true\"";
    internal const string DuplicateLinePathSuffix = "\"/><line number=\"1\" hits=\"0\"/>";
    internal const string DuplicateBranchSuffix = ")\"/><line number=\"1\" hits=\"1\" branch=\"true\" condition-coverage=\"69% (69/100)\"/>";
    internal const string DuplicateBranchCaseVariantSuffix = ")\"/><line number=\"1\" hits=\"1\" branch=\"True\" condition-coverage=\"70% (70/100)\"/>";
    internal const string HashFileRelativePath = "src/KeyLoad.Analyzers/Features/CodeQuality/Analyzers/LiteralMachineKeyAnalyzer.cs";
    internal const string UnexpectedSourceFileName = "Unexpected.cs";
    internal const string ProcessName = "pwsh";
    internal const string ModePrepare = "Prepare";
    internal const string ModeVerify = "Verify";
    internal const string ParameterMode = "-Mode";
    internal const string ParameterRepository = "-Repository";
    internal const string ParameterContract = "-Contract";
    internal const string ParameterEvidence = "-EvidenceRoot";
    internal const string ParameterCoverage = "-CoverageReport";
}
