<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="ManagedCode.Communication" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Orleans.Serialization" />
    <PackageReference Include="Microsoft.Orleans.CodeGenerator" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="KeyLoad.Query" />
    <InternalsVisibleTo Include="KeyLoad.Server" />
    <InternalsVisibleTo Include="KeyLoad.Client" />
    <InternalsVisibleTo Include="KeyLoad.UnitTests" />
    <InternalsVisibleTo Include="KeyLoad.Core" />
    <InternalsVisibleTo Include="KeyLoad.Orleans" />
    <InternalsVisibleTo Include="KeyLoad.RecoveryTests" />
  </ItemGroup>
</Project>
