namespace KeyLoad.AppHost.Features.TestInfrastructure;

internal static class TestSuiteProtocol
{
    internal const string AnalyzersSuite = "analyzers";
    internal const string UnitSuite = "unit";
    internal const string ScalarUnitSuite = "unit-scalar";
    internal const string RecoverySuite = "recovery";
    internal const string Rf3Suite = "rf3";
    internal const string ComparisonSuite = "comparison";
    internal const string SiteSuite = "site";
    internal const string AnalyzerTestProjectName = "KeyLoad.Analyzers.Tests";
    internal const string UnitTestProjectName = "KeyLoad.UnitTests";
    internal const string RecoveryTestProjectName = "KeyLoad.RecoveryTests";
    internal const string IntegrationTestProjectName = "KeyLoad.IntegrationTests";
    internal const string ComparisonTestProjectName = "KeyLoad.ComparisonTests";
    internal const string SiteTestProjectName = "KeyLoad.SiteTests";
    internal const string SuiteSetting = "KeyLoadTests:Suite";
    internal const string SuiteEnvironment = "KeyLoadTests__Suite";
    internal const string VectorProfileSetting = "KeyLoadTests:VectorProfile";
    internal const string VectorProfileEnvironment = "KeyLoadTests__VectorProfile";
    internal const string ScaleProfileSetting = "KeyLoadTests:ScaleProfile";
    internal const string ScaleProfileEnvironment = "KeyLoadTests__ScaleProfile";
    internal const string FilterSetting = "KeyLoadTests:Filter";
    internal const string TimeoutSetting = "KeyLoadTests:TimeoutMinutes";
    internal const string OpenLoopRateSetting = "KeyLoadTests:OpenLoopRate";
    internal const string OpenLoopRateEnvironment = "KeyLoadTests__OpenLoopRate";
    internal const string OpenLoopNativeRateEnvironment = "Benchmarks__OpenLoopRate";
    internal const string OpenLoopCancellationProofSetting = "Benchmarks:OpenLoopCancellationProof";
    internal const string BenchmarkEnabledSetting = "Benchmarks:Enabled";
    internal const string BenchmarkConfigurationSection = "Benchmarks";
    internal const string ConfigurationKeySeparator = ":";
    internal const string DocumentsWorkloadSettingName = "Documents";
    internal const string OperationsWorkloadSettingName = "Operations";
    internal const string WarmupWorkloadSettingName = "Warmup";
    internal const string RepetitionsWorkloadSettingName = "Repetitions";
    internal const string ConcurrencyWorkloadSettingName = "Concurrency";
    internal const string PayloadBytesWorkloadSettingName = "PayloadBytes";
    internal const string SeedWorkloadSettingName = "Seed";
    internal const string DimensionsWorkloadSettingName = "Dimensions";
    internal const string TopKWorkloadSettingName = "TopK";
    internal const string TimeoutSecondsWorkloadSettingName = "TimeoutSeconds";
    internal const string GraphVerticesWorkloadSettingName = "GraphVertices";
    internal const string GraphFanOutWorkloadSettingName = "GraphFanOut";
    internal const string GraphDepthWorkloadSettingName = "GraphDepth";
    internal const string AppHostBenchmarkProfileSetting = "Benchmarks:Profile";
    internal const string GeneralComparisonAppHostProfile = "general";
    internal const string ProfileTimeoutMinutesText = "140";
    internal const string IsolatedComparisonFilter = "/*/*/IsolatedNativeComparisonTests/*";
    internal const string ArgumentPrefix = "--";
    internal const string ArgumentValueSeparator = "=";
}
