<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="KeyLoad.RecoveryTests" />
    <InternalsVisibleTo Include="KeyLoad.UnitTests" />
    <ProjectReference Include="../../src/KeyLoad.Core/KeyLoad.Core.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Query/KeyLoad.Query.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Server/KeyLoad.Server.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Security/KeyLoad.Security.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Replication/KeyLoad.Replication.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Storage.ZoneTree/KeyLoad.Storage.ZoneTree.csproj" />
  </ItemGroup>
</Project>
