namespace KeyLoad.SiteTests.Features.BenchmarkComparisons;

internal static class SiteBrowserUiTokens
{
    public const string SelectorResultPanel = "#results-panel";
    public const string SelectorScene = "#cluster-scene";
    public const string SelectorSceneStatus = "[data-scene-status]";
    public const string SelectorMotion = "#scene-motion";
    public const string SceneStateAttribute = "data-scene-state";
    public const string BackendAttribute = "data-graphics-backend";
    public const string FrameAttribute = "data-frame-state";
    public const string BufferPixelsAttribute = "data-buffer-pixels";
    public const string DrawCallsAttribute = "data-draw-calls";
    public const string RenderCallsAttribute = "data-render-calls";
    public const string TrianglesAttribute = "data-triangles";
    public const string StateReady = "ready";
    public const string StateUnsupported = "unsupported";
    public const string StatePaused = "paused";
    public const string StateError = "error";
    public const string FrameRendered = "rendered";
    public const string FrameField = "frame";
    public const string SceneStateField = "state";
    public const string ScenePoster = "poster";
    public const string BackendWebGpu = "webgpu";
    public const string BackendWebGl = "webgl2";
    public const string BackendUnknown = "unknown";
    public const string RuntimeErrorEvent = "Runtime.exceptionThrown";
    public const string ConsoleEvent = "Log.entryAdded";
    public const string RuntimeConsoleEvent = "Runtime.consoleAPICalled";
    public const string ConsoleTypeField = "type";
    public const string ConsoleArgumentsField = "args";
    public const string ConsoleErrorType = "error";
    public const string ConsoleAssertType = "assert";
    public const string ConsoleValueField = "value";
    public const string ConsoleDescriptionField = "description";
    public const string ConsoleMessageSeparator = " ";
    public const string ConsoleEntryField = "entry";
    public const string ConsoleLevelField = "level";
    public const string KeyboardKeyDown = "keyDown";
    public const string KeyboardKeyUp = "keyUp";
    public const string ArrowRight = "ArrowRight";
    public const string ErrorLevel = "error";
    public const string CanvasCountField = "canvasCount";
    public const string BackendField = "backend";
    public const string SceneStatusField = "status";
    public const string BufferPixelsField = "bufferPixels";
    public const string CanvasWidthField = "canvasWidth";
    public const string CanvasHeightField = "canvasHeight";
    public const string PixelRatioField = "pixelRatio";
    public const string DrawCallsField = "drawCalls";
    public const string RenderCallsField = "renderCalls";
    public const string TrianglesField = "triangles";
    public const string NoScriptSelector = "noscript";
    public const string OverflowScript = "document.documentElement.scrollWidth>window.innerWidth";
    public const string SceneScrollScript = "document.querySelector('#cluster-scene')?.scrollIntoView({block:'center',behavior:'instant'})";
    public const string SceneSnapshotScript = "({backend:document.querySelector('#cluster-scene')?.getAttribute('data-graphics-backend'),status:document.querySelector('" + SelectorSceneStatus + "')?.textContent,frame:document.querySelector('#cluster-scene')?.getAttribute('data-frame-state'),canvasCount:document.querySelectorAll('#cluster-scene canvas').length,bufferPixels:Number(document.querySelector('#cluster-scene')?.getAttribute('data-buffer-pixels')??0),drawCalls:Number(document.querySelector('#cluster-scene')?.getAttribute('data-draw-calls')??0),triangles:Number(document.querySelector('#cluster-scene')?.getAttribute('data-triangles')??0)})";
    public const string MotionEnableScript = "(()=>{const e=document.querySelector('#scene-motion');if(!e||e.disabled)return false;if(e.getAttribute('aria-pressed')!=='true')e.click();return e.getAttribute('aria-pressed')==='true'})()";
    public const string MotionDisableScript = "(()=>{const e=document.querySelector('#scene-motion');if(!e||e.disabled)return false;if(e.getAttribute('aria-pressed')==='true')e.click();return e.getAttribute('aria-pressed')==='false'})()";
    public const string MotionAvailableScript = "document.querySelector('#scene-motion')?.disabled===false";
    public const string MotionPlayingScript = "document.querySelector('#scene-motion')?.getAttribute('aria-pressed')==='true'";
    public const string ReducedMotionScript = "matchMedia('(prefers-reduced-motion: reduce)').matches";
    public const string TableScrollLabelScript = "document.querySelector('.table-scroll')?.getAttribute('aria-label')";
    public const string ScrollLabelToken = "scroll";
    public const string NoScriptEvidenceLabel = "GitHub comparison evidence";
    public const string HtmlField = "outerHTML";
    public const string SceneScrollAwayScript = "window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'})";
    public const string SceneIdleSnapshotScript = "({state:document.querySelector('#cluster-scene')?.getAttribute('data-scene-state')??'poster',canvasCount:document.querySelectorAll('#cluster-scene canvas').length})";
    public const string SceneBenchmarkFragmentScript = "window.location.hash==='" + SiteBrowserTokens.PageHideFragment + "'";
    public const string ScenePausedScript = "document.querySelector('#cluster-scene')?.getAttribute('data-frame-state')==='paused'";
    public const string MotionDisabledScript = "document.querySelector('#scene-motion')?.disabled===true";
    public const string SceneGeometrySnapshotScript = "(()=>{const host=document.querySelector('#cluster-scene');const canvas=host?.querySelector('canvas');return{canvasCount:host?.querySelectorAll('canvas').length??0,canvasWidth:canvas?.width??0,canvasHeight:canvas?.height??0,pixelRatio:host&&canvas?Math.max(canvas.width/host.clientWidth,canvas.height/host.clientHeight):0,frame:host?.getAttribute('data-frame-state'),bufferPixels:Number(host?.getAttribute('data-buffer-pixels')??0),drawCalls:Number(host?.getAttribute('data-draw-calls')??0),renderCalls:Number(host?.getAttribute('data-render-calls')??0),triangles:Number(host?.getAttribute('data-triangles')??0)}})()";
    public const string SceneCenterScript = "(()=>{const r=document.querySelector('#cluster-scene').getBoundingClientRect();return{x:r.left+r.width/4,y:r.top+r.height/4}})()";
    public const string GeometryStableScript = "(()=>{const host=document.querySelector('#cluster-scene');return host?.getAttribute('data-frame-state')==='rendered'&&host?.querySelector('canvas')!==null})()";
    public const string SceneReadyScript = "new Promise(resolve => { const started = performance.now(); const check = () => { const node = document.querySelector('#cluster-scene'); const state = node?.dataset.sceneState ?? 'poster'; if (state === 'ready' || state === 'unsupported' || state === 'error') resolve(state); else if (performance.now() - started > 20000) resolve(state); else setTimeout(check, 40); }; check(); })";
    public const string WaitScriptPrefix = "new Promise(resolve => { const started = performance.now(); const check = () => { if (";
    public const string WaitScriptSuffix = ") resolve(true); else if (performance.now() - started > 15000) resolve(false); else setTimeout(check, 20); }; check(); })";
    public const string BrowserWaitScript = "document.readyState === 'complete' && document.querySelector('#results-panel')?.getAttribute('aria-busy') === 'false'";
    public const string ReducedMotionFeature = "prefers-reduced-motion";
    public const string ReducedMotionValue = "reduce";
    public const string EmulationFeatureName = "name";
    public const string EmulationFeatureValue = "value";
    public const int RendererPixelLimit = 1_000_000;
    public const int RendererDrawCallLimit = 30;
    public const int RendererTriangleLimit = 5000;
    public const double RendererPixelRatioLimit = 1.5d;
    public const int ViewportDesktopWidth = 1440;
    public const int ViewportTabletWidth = 768;
    public const int ViewportMobileWidth = 390;
    public const int ViewportNarrowWidth = 320;
    public const int ViewportMobileHeight = 844;
    public const int ScenePosterWaitMilliseconds = 1000;
    public const int SceneSettleWaitMilliseconds = 500;
    public const int SceneIdleWaitMilliseconds = 100;
    public const int NoScriptWaitAttempts = 100;
    public const int NoScriptPollMilliseconds = 50;
    public static readonly int[] ViewportWidths = [ViewportDesktopWidth, ViewportTabletWidth, ViewportMobileWidth, ViewportNarrowWidth];
}
