namespace KeyLoad.SiteTests.Features.BenchmarkComparisons;

internal static class SiteGitHubEvidenceTokens
{
    public const string CaptureEnvironment = "KEYLOAD_SITE_GITHUB_CAPTURE";
    public const string ArchiveEnvironment = "KEYLOAD_SITE_ARCHIVE";
    public const string SiteRevisionEnvironment = "KEYLOAD_SITE_SOURCE_REVISION";
    public const string WorkflowRevisionEnvironment = SitePublicationTokens.ControlRevisionEnvironment;
    public const string CliModule = "scripts/Features/BenchmarkComparisons/github-evidence.mjs";
    public const string CaptureDirectory = "capture";
    public const string ArchiveFile = "comparison-suite.zip";
    public const string BeforeReceiptFile = "before-receipt.json";
    public const string AfterReceiptFile = "after-receipt.json";
    public const string WorkflowCapture = "workflow.json";
    public const string RunsCapture = "runs-pages.json";
    public const string SelectedRunCapture = "run.json";
    public const string JobsCapture = "jobs-pages.json";
    public const string ArtifactsCapture = "artifacts-pages.json";
    public const string AttemptsDirectory = "attempts";
    public const string ComparisonSuiteArtifact = "comparison-suite";
    public const string RepositoryFullName = "managedcode/KeyLoad";
    public const string WorkflowPath = ".github/workflows/ci.yml";
    public const string WorkflowDisplayName = "CI";
    public const string WorkflowName = "KeyLoad CI";
    public const string ComparisonJobName = "comparison-smoke";
    public const string ControlledOtherName = "controlled-unrelated-entry";
    public const string DotnetComparisonStep = "Run dotnet test --project tests/KeyLoad.ComparisonTests --no-build --no-restore --configuration Release";
    public const string SmallMeasurementStep = "Measure 1 KiB documents, eight clients and three graph hops";
    public const string LargeMeasurementStep = "Measure 16 KiB documents, four clients and five graph hops";
    public const string CommandSelect = "select";
    public const string CommandProve = "prove";
    public const string CommandVerifyArchive = "verify-archive";
    public const string CommandFresh = "fresh";
    public const string ModeValidate = "validate";
    public const string ModePublish = "publish";
    public const string ArgumentInput = "--input=";
    public const string ArgumentMode = "--mode=";
    public const string ArgumentRequestedRun = "--requested-run=";
    public const string ArgumentSiteRevision = "--site-revision=";
    public const string ArgumentWorkflowRevision = "--workflow-revision=";
    public const string ArgumentReceipt = "--receipt=";
    public const string ArgumentArchive = "--archive=";
    public const string ArgumentBefore = "--before=";
    public const string ArgumentAfter = "--after=";
    public const string State = "state";
    public const string NeedsAttempt = "needs_attempt";
    public const string Selected = "selected";
    public const string Unavailable = "unavailable";
    public const string MetadataVerified = "metadata_verified";
    public const string ArchiveVerified = "archive_verified";
    public const string NoSuccessfulComparison = "no_successful_comparison";
    public const string PublishEligible = "publishEligible";
    public const string RunId = "runId";
    public const string RunNumber = "runNumber";
    public const string RunAttempt = "runAttempt";
    public const string Run = "run";
    public const string RunNumberReceipt = "number";
    public const string RunAttemptNested = "attempt";
    public const string MeasuredRevision = "measuredSourceRevision";
    public const string ComparisonJobId = "comparisonJobId";
    public const string ComparisonJob = "comparisonJob";
    public const string Artifact = "artifact";
    public const string MetadataFiles = "metadataFiles";
    public const string Archive = "archive";
    public const string Fresh = "fresh";
    public const string Repository = "repository";
    public const string FullName = "fullName";
    public const string Workflow = "workflow";
    public const string Path = "path";
    public const string WorkflowId = "workflowId";
    public const string WorkflowPathProperty = "workflowPath";
    public const string SiteSourceRevision = "siteSourceRevision";
    public const string ControlWorkflowRevision = "controlWorkflowRevision";
    public const string ComparisonJobUrl = "url";
    public const string StartedAt = "startedAt";
    public const string CompletedAt = "completedAt";
    public const string Steps = "steps";
    public const string StepName = "name";
    public const string StepNumber = "number";
    public const int OversizedArtifact = ArchiveBytes + One;
    public const string ArtifactId = SiteTokens.Id;
    public const string ArtifactName = StepName;
    public const string ArtifactSize = "sizeBytes";
    public const string ArtifactDigest = "digest";
    public const string ArtifactCreatedAt = "createdAt";
    public const string ArtifactSha256 = "sha256";
    public const string ArtifactBytes = "bytes";
    public const string ArtifactDigestPrefix = "sha256:";
    public const string FilePath = Path;
    public const string FileSha256 = ArtifactSha256;
    public const string WorkflowState = State;
    public const string WorkflowIdField = ArtifactId;
    public const string TotalCount = "total_count";
    public const string WorkflowRuns = "workflow_runs";
    public const string Jobs = "jobs";
    public const string Artifacts = "artifacts";
    public const string RunNumberField = "run_number";
    public const string RunAttemptField = "run_attempt";
    public const string RunIdField = "run_id";
    public const string Event = "event";
    public const string Status = SiteTokens.Status;
    public const string Conclusion = "conclusion";
    public const string HeadBranch = "head_branch";
    public const string HeadSha = "head_sha";
    public const string WorkflowIdFieldRun = "workflow_id";
    public const string RepositoryId = "repository_id";
    public const string HeadRepositoryId = "head_repository_id";
    public const string RepositoryObject = Repository;
    public const string HeadRepositoryObject = "head_repository";
    public const string RepositoryFullNameField = "full_name";
    public const string Url = "html_url";
    public const string StepNumberField = StepNumber;
    public const string CreatedAt = "created_at";
    public const string SizeInBytes = "size_in_bytes";
    public const string Expired = "expired";
    public const string WorkflowRun = "workflow_run";
    public const string RunStartedAt = "started_at";
    public const string RunCompletedAt = "completed_at";
    public const string MainRefCapture = "main-ref.json";
    public const string Object = "object";
    public const string Sha = "sha";
    public const string ErrorCode = "code";
    public const string ErrorMessage = "message";
    public const string ErrorArgument = "E_ARGUMENT";
    public const string ErrorCapture = "E_CAPTURE";
    public const string ErrorPagination = "E_PAGINATION";
    public const string ErrorWorkflow = "E_WORKFLOW";
    public const string ErrorRun = "E_RUN";
    public const string ErrorJob = "E_JOB";
    public const string ErrorArtifact = "E_ARTIFACT";
    public const string ErrorArchive = "E_ARCHIVE";
    public const string ErrorSource = "E_SOURCE";
    public const string ErrorFreshness = "E_FRESHNESS";
    public const string CliFailure = "The real GitHub evidence CLI failed to start.";
    public const string CliTimeout = "The GitHub evidence CLI exceeded its bounded timeout.";
    public const string CaptureMissing = "Required authenticated GitHub evidence inputs are unavailable.";
    public const string CaptureNotAbsolute = "GitHub evidence input paths must be absolute.";
    public const string CaptureCopyPattern = "*";
    public const string NodeV8CoverageEnvironment = "NODE_V8_COVERAGE";
    public const string PathEnvironment = "PATH";
    public const string WrongRepository = "another/repository";
    public const string WrongWorkflowPath = ".github/workflows/other.yml";
    public const string WrongEvent = "pull_request";
    public const string WrongBranch = "topic";
    public const string WrongConclusion = "failure";
    public const string PendingStatus = "queued";
    public const string SkippedConclusion = "skipped";
    public const string WrongRevision = "0000000000000000000000000000000000000000";
    public const string InvalidDate = "not-a-date";
    public const string InvalidDigest = "sha256:invalid";
    public const string NoncanonicalMetadataPath = "./workflow.json";
    public const string TraversalMetadataPath = "../workflow.json";
    public const string InvalidStepName = "controlled-unknown-step";
    public const string InvalidMode = "controlled-invalid-mode";
    public const string InvalidSourceRevision = "invalid-revision";
    public const string RelativeCapture = "controlled-relative-capture";
    public const string UnknownArgument = "--controlled-unknown=value";
    public const string CliEnvelopeOk = "ok";
    public const string CliEnvelopeResult = "result";
    public const string CliEnvelopeError = "error";
    public const string Json = "json";
    public const string OutputReceipt = "receipt.json";
    public const int First = 0;
    public const int Next = 1;
    public const int Zero = 0;
    public const int One = 1;
    public const int ExpectedSteps = 3;
    public const int JobUnavailableScenarios = 3;
    public const string ReceiptFile = "metadata-receipt.json";
    public const string MutatedCaptureFile = "mutated-capture.json";
    public const string ModeField = "mode";
    public const string ArtifactSizeBytes = "sizeBytes";
    public const string RunUrl = "url";
    public const string SiteRevision = "siteSourceRevision";
    public const string MetadataFileName = "metadata.json";
    public const string RoundTripDateFormat = "O";
    public const char DigestZero = '0';
    public const char DigestOne = '1';
    public const byte ByteToggle = 1;
    public const int MaxRuns = 1000;
    public const int MaxPairs = 10000;
    public const int HistoryTimeoutMilliseconds = 120000;
    public const int MetadataBytes = 16_777_216;
    public const int ArchiveBytes = 134_217_728;
    public const int ShaLength = SiteTokens.ShaLength;
    public static readonly string[] MeasurementStepNames =
    [
        DotnetComparisonStep,
        SmallMeasurementStep,
        LargeMeasurementStep,
    ];
    public static readonly string[] RequiredCaptureFiles =
    [WorkflowCapture, RunsCapture, SelectedRunCapture, JobsCapture, ArtifactsCapture];
}
