<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/KeyLoad.Replication/KeyLoad.Replication.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Security/KeyLoad.Security.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Storage.ZoneTree/KeyLoad.Storage.ZoneTree.csproj" />
    <ProjectReference Include="../KeyLoad.CrashHost/KeyLoad.CrashHost.csproj" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
</Project>
