<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/KeyLoad.Query/KeyLoad.Query.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Security/KeyLoad.Security.csproj" />
    <ProjectReference Include="../../src/KeyLoad.Storage.ZoneTree/KeyLoad.Storage.ZoneTree.csproj" />
    <PackageReference Include="BenchmarkDotNet" />
    <InternalsVisibleTo Include="KeyLoad.UnitTests" />
  </ItemGroup>
</Project>
