using Microsoft.CodeAnalysis;

namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-004: verifies orleans generate serializer tests with real compiler fixtures.</summary>
internal sealed class OrleansGenerateSerializerTests
{
    private const string Id = OrleansGenerateSerializerAnalyzer.DiagnosticId;

    /// <summary>Verifies id member without serializer reports located error.</summary>
    [Test]
    public async Task IdMemberWithoutSerializerReportsLocatedErrorAsync()
    {
        const string source = """
            public sealed class MissingSerializer
            {
                [Orleans.Id(0)] public string Value { get; set; } = string.Empty;
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new OrleansGenerateSerializerAnalyzer(),
            source, AnalyzerFixture.CoreAssembly);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            source, "MissingSerializer");
    }

    /// <summary>Verifies nested grain payload without serializer reports located error.</summary>
    [Test]
    public async Task NestedGrainPayloadWithoutSerializerReportsLocatedErrorAsync()
    {
        const string source = """
            public sealed record MissingPayload(string Value);
            public interface IExampleGrain : Orleans.IGrainWithStringKey
            {
                System.Threading.Tasks.Task<System.Collections.Generic.List<MissingPayload>> ReadAsync();
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new OrleansGenerateSerializerAnalyzer(),
            source);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            source, "MissingPayload");
    }

    /// <summary>Verifies persistent state without serializer reports located error.</summary>
    [Test]
    public async Task PersistentStateWithoutSerializerReportsLocatedErrorAsync()
    {
        const string source = """
            public sealed class MissingState;
            public sealed class ExampleGrain(Orleans.Runtime.IPersistentState<MissingState> state);
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new OrleansGenerateSerializerAnalyzer(),
            source);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            source, "MissingState");
    }

    /// <summary>Verifies serialized payload and ordinary dto are allowed.</summary>
    [Test]
    public async Task SerializedPayloadAndOrdinaryDtoAreAllowedAsync()
    {
        const string source = """
            [Orleans.GenerateSerializer]
            public sealed class Payload
            {
                [Orleans.Id(0)] public string Value { get; set; } = string.Empty;
            }
            public sealed record HttpDto(string Value);
            public interface IExampleGrain : Orleans.IGrainWithStringKey
            {
                System.Threading.Tasks.Task<Payload> ReadAsync();
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new OrleansGenerateSerializerAnalyzer(),
            source);
        await Assert.That(findings).IsEmpty();
    }

    /// <summary>Verifies external test and generated assemblies are ignored.</summary>
    [Test]
    public async Task ExternalTestAndGeneratedAssembliesAreIgnoredAsync()
    {
        const string source = """
            public sealed class MissingSerializer
            {
                [Orleans.Id(0)] public string Value { get; set; } = string.Empty;
            }
            """;
        var external = await AnalyzerFixture.AnalyzeAsync(new OrleansGenerateSerializerAnalyzer(),
            source, AnalyzerFixture.ExternalAssembly);
        var tests = await AnalyzerFixture.AnalyzeAsync(new OrleansGenerateSerializerAnalyzer(),
            source, AnalyzerFixture.CoreTestAssembly);
        var unitTests = await AnalyzerFixture.AnalyzeAsync(new OrleansGenerateSerializerAnalyzer(),
            source, AnalyzerFixture.UnitTestAssembly);
        var generated = await AnalyzerFixture.AnalyzeAsync(new OrleansGenerateSerializerAnalyzer(),
            "// <auto-generated/>\n" + source, path: AnalyzerFixture.GeneratedPath);
        await Assert.That(external).IsEmpty();
        await Assert.That(tests).IsEmpty();
        await Assert.That(unitTests).IsEmpty();
        await Assert.That(generated).IsEmpty();
    }
}
