using Microsoft.CodeAnalysis;

namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-004: verifies program endpoint mapping tests with real compiler fixtures.</summary>
internal sealed class ProgramEndpointMappingTests
{
    private const string Id = ProgramEndpointMappingAnalyzer.DiagnosticId;
    private const string Source = """
        using Microsoft.AspNetCore.Builder;
        var app = WebApplication.CreateBuilder().Build();
        app.MapKeyLoadApi();
        app.MapGet("/direct", () => "ok");
        """;
    private const string AggregateSource = """
        using Microsoft.AspNetCore.Builder;
        internal static class KeyLoadEndpoints
        {
            internal static WebApplication MapKeyLoadApi(this WebApplication app)
            {
                app.MapGet("/aggregate", () => "ok");
                return app;
            }
        }
        """;

    /// <summary>Verifies direct mapping in server program reports located error.</summary>
    [Test]
    public async Task DirectMappingInServerProgramReportsLocatedErrorAsync()
    {
        var findings = await AnalyzerFixture.AnalyzeAsync(new ProgramEndpointMappingAnalyzer(),
            Source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ProgramPath,
            executable: true, additionalSource: AggregateSource);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            Source, "app.MapGet", AnalyzerFixture.ProgramPath);
    }

    /// <summary>Verifies aggregate mapping is allowed.</summary>
    [Test]
    public async Task AggregateMappingIsAllowedAsync()
    {
        const string source = """
            using Microsoft.AspNetCore.Builder;
            var app = WebApplication.CreateBuilder().Build();
            app.MapKeyLoadApi();
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new ProgramEndpointMappingAnalyzer(),
            source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ProgramPath,
            executable: true, additionalSource: AggregateSource);
        await Assert.That(findings).IsEmpty();
    }

    /// <summary>Verifies direct mapping outside server program is ignored.</summary>
    [Test]
    public async Task DirectMappingOutsideServerProgramIsIgnoredAsync()
    {
        var external = await AnalyzerFixture.AnalyzeAsync(new ProgramEndpointMappingAnalyzer(),
            Source, AnalyzerFixture.ExternalAssembly, AnalyzerFixture.ProgramPath,
            executable: true, additionalSource: AggregateSource);
        var extension = await AnalyzerFixture.AnalyzeAsync(new ProgramEndpointMappingAnalyzer(),
            Source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ServerEndpointsPath,
            executable: true, additionalSource: AggregateSource);
        await Assert.That(external).IsEmpty();
        await Assert.That(extension).IsEmpty();
    }

    /// <summary>Verifies generated server program is ignored.</summary>
    [Test]
    public async Task GeneratedServerProgramIsIgnoredAsync()
    {
        var findings = await AnalyzerFixture.AnalyzeAsync(new ProgramEndpointMappingAnalyzer(),
            "// <auto-generated/>\n" + Source, AnalyzerFixture.ServerAssembly, AnalyzerFixture.ProgramPath,
            executable: true, additionalSource: AggregateSource);
        await Assert.That(findings).IsEmpty();
    }
}
