using Microsoft.CodeAnalysis;

namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-004: verifies system clock access tests with real compiler fixtures.</summary>
internal sealed class SystemClockAccessTests
{
    private const string Id = SystemClockAccessAnalyzer.DiagnosticId;

    /// <summary>Verifies direct utc now reports located error.</summary>
    [Test]
    public async Task DirectUtcNowReportsLocatedErrorAsync()
    {
        const string source = """
            internal static class Subject
            {
                internal static System.DateTime Now() => System.DateTime.UtcNow;
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new SystemClockAccessAnalyzer(), source);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Error,
            source, "System.DateTime.UtcNow");
    }

    /// <summary>Verifies time provider and non clock property are allowed.</summary>
    [Test]
    public async Task TimeProviderAndNonClockPropertyAreAllowedAsync()
    {
        const string source = """
            internal sealed class Subject(System.TimeProvider timeProvider)
            {
                internal System.DateTimeOffset Now() => timeProvider.GetUtcNow();
                internal static System.DateTime Min() => System.DateTime.MinValue;
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new SystemClockAccessAnalyzer(), source);
        await Assert.That(findings).IsEmpty();
    }

    /// <summary>Verifies generated clock code is ignored.</summary>
    [Test]
    public async Task GeneratedClockCodeIsIgnoredAsync()
    {
        const string source = """
            // <auto-generated/>
            internal static class Subject
            {
                internal static System.DateTimeOffset Now() => System.DateTimeOffset.Now;
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new SystemClockAccessAnalyzer(), source,
            path: AnalyzerFixture.GeneratedPath);
        await Assert.That(findings).IsEmpty();
    }
}
