using Microsoft.CodeAnalysis;

namespace KeyLoad.Analyzers.Tests.Features.CodeQuality;

/// <summary>AC-CQ-004: verifies untyped catch tests with real compiler fixtures.</summary>
internal sealed class UntypedCatchTests
{
    private const string Id = UntypedCatchAnalyzer.DiagnosticId;

    /// <summary>Verifies untyped catch reports located warning.</summary>
    [Test]
    public async Task UntypedCatchReportsLocatedWarningAsync()
    {
        const string source = """
            internal static class Subject
            {
                internal static void Run()
                {
                    try { System.Console.WriteLine(); }
                    catch { System.Console.WriteLine(); }
                }
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new UntypedCatchAnalyzer(), source);
        await AnalyzerFixture.AssertFindingAsync(findings, Id, DiagnosticSeverity.Warning,
            source, "catch {");
    }

    /// <summary>Verifies explicit exception type is allowed.</summary>
    [Test]
    public async Task ExplicitExceptionTypeIsAllowedAsync()
    {
        const string source = """
            internal static class Subject
            {
                internal static void Run()
                {
                    try { System.Console.WriteLine(); }
                    catch (System.Exception) { System.Console.WriteLine(); }
                }
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new UntypedCatchAnalyzer(), source);
        await Assert.That(findings).IsEmpty();
    }

    /// <summary>Verifies generated catch is ignored.</summary>
    [Test]
    public async Task GeneratedCatchIsIgnoredAsync()
    {
        const string source = """
            // <auto-generated/>
            internal static class Subject
            {
                internal static void Run()
                {
                    try { System.Console.WriteLine(); }
                    catch { System.Console.WriteLine(); }
                }
            }
            """;
        var findings = await AnalyzerFixture.AnalyzeAsync(new UntypedCatchAnalyzer(), source,
            path: AnalyzerFixture.GeneratedPath);
        await Assert.That(findings).IsEmpty();
    }
}
