<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="KeyLoad.Orleans" />
    <InternalsVisibleTo Include="KeyLoad.Server" />
    <InternalsVisibleTo Include="KeyLoad.Query" />
    <ProjectReference Include="../KeyLoad.Abstractions/KeyLoad.Abstractions.csproj" />
    <PackageReference Include="ManagedCode.TimeSeries" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
  </ItemGroup>
</Project>
